name: GitHub Actions Build
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      storePass: ${{ secrets.KEY_STORE_PASS }}
      keyAlias: ${{ secrets.KEY_ALIAS }}
      keyPass: ${{ secrets.KEY_PASS }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Detekt - check the code style
        run: ./gradlew detekt
      - name: Run all unit tests
        run: ./gradlew testDebugUnitTest
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Archive outputs
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/mapping/release/mapping.txt
